spring:
  mail:
    host: smtp.naver.com
    port: 465
    username: syhoneyjam@naver.com
    password: mingsae123!@
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true